### PR TITLE
Properly merge RContextForwardableStuff

### LINKED ISSUE #4: Parallel runtime fails to schedule actions sometimes
I've been working on implementing the MatMul benchmark, and have come across a bug, where an action isn't scheduled, even though it should be. The important reaction is [here](https://github.com/lf-lang/lingua-franca/blob/rust-more-benchmarks/benchmark/Rust/Savina/src/parallelism/MatMul.lf#L87). When `data` is set on line 93, the connected reactions in `Worker` trigger, but the reaction to `next` seems to never trigger, even though it is scheduled at the end of the same reaction.\
This problem disappears when I remove the `parallel-runtime` feature.

Here is the execution trace:
```
[2021-12-17T11:35:38Z INFO ] Assembling runner
[2021-12-17T11:35:38Z INFO ] Assembling manager
[2021-12-17T11:35:38Z INFO ] Assembling workers
[2021-12-17T11:35:38Z INFO ] Registering workers
[2021-12-17T11:35:38Z INFO ] Registering manager
[2021-12-17T11:35:38Z INFO ] Registering runner
[2021-12-17T11:35:38Z INFO ] Triggering startup...
[2021-12-17T11:35:38Z TRACE]   - Level 1
[2021-12-17T11:35:38Z TRACE]   - Executing /runner/0
[2021-12-17T11:35:38Z TRACE]   - Executing /0
Benchmark: MatMulBenchmark
Arguments:
            numIterations = 12
               dataLength = 1024
[2021-12-17T11:35:38Z TRACE]   - Executing /manager/0
           blockThreshold = 16384
               priorities = 10
               numWorkers = 20
System information:
                 O/S Name = Linux
[2021-12-17T11:35:38Z TRACE] Pushing at (T0 + 0 ns = 0 ms, 1): run [2: {/runner/1}]
[2021-12-17T11:35:38Z TRACE] Processing event at (T0 + 0 ns = 0 ms, 1): run [2: {/runner/1}]
[2021-12-17T11:35:38Z TRACE]   - Running late by 136662519 ns = 136662 µs = 136 ms
[2021-12-17T11:35:38Z TRACE]   - Level 2
[2021-12-17T11:35:38Z TRACE]   - Executing /runner/1 (level 2)
[2021-12-17T11:35:38Z TRACE]   - Level 5
[2021-12-17T11:35:38Z TRACE]   - Executing /manager/1 (level 5)
[2021-12-17T11:35:38Z TRACE]   - Level 8
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[15]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[8]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[3]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[4]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[17]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[2]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[9]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[16]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[0]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[19]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[5]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[13]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[12]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[11]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[14]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[6]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[18]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[10]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[1]/0
[2021-12-17T11:35:38Z TRACE]   - Executing /workers[7]/0
[2021-12-17T11:35:38Z TRACE] Will wait for asynchronous event without timeout
[2021-12-17T11:35:38Z INFO ] Event queue is empty forever, shutting down.
[2021-12-17T11:35:38Z INFO ] Scheduler is shutting down, at (T0 + 137417726 ns = 137 ms, 0)
[2021-12-17T11:35:38Z INFO ] Scheduler has been shut down

```

### PR DESCRIPTION
**Pull request by jhaye**
This is a quick fix for #4. Previously `ctx.insides` were replaced after executing a tag, instead of merged. I have confirmed that this works, but won't have the time to do proper performance testing for some time. Better working with potentially bad performance than broken I guess.

Closes #4

### CODE REVIEW

File: src/scheduler/context.rs [hunk 1]
```diff
@@ -558,6 +558,11 @@ impl RContextForwardableStuff<'_> {
         self.future_events.append(&mut other.future_events);
```
Comment (oowekyala) [inline src/scheduler/context.rs:558]: You could now make this merge function use the other to remove code duplication.

**Comment by jhaye** [comment]
Thanks for the suggestions!

**Review by oowekyala — APPROVED** [review]
LGTM! Last minor comment, do what you want with this: I usually prefer the name `merge` for symmetric operations, eg `merge(a, b)`, and `absorb` for assymetric ones (ie, merge in place), like `a.absorb(b)`, as I find it reads better. I used this convention in this codebase ([ref](https://github.com/lf-lang/reactor-rust/search?q=absorb&type=code)), maybe it's worth keeping this going

**Comment by jhaye** [comment]
Yes, I think this terminology makes sense :+1:

**Comment by cmnrd** [comment]
Great! Thanks!
